version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: "fleet-management"
      POSTGRES_USER: "atom"
      POSTGRES_PASSWORD: "atom"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
