app:
  replicaCount: 1
  image:
    repository: "gitlab.e-kama.com:5050/b2b-portal/backend/fleet-management-service"
    tag: "develop"
  env:
    PG_HOST: portal-db01.dev.e-kama.com
    PG_PORT: 5432
    PG_USER: fleet-management-service
    PG_PASSWORD: P9225HmI08hb
    PG_DB: fleet-management-service
    DEBUG: true
    KEYCLOAK_SERVER_URL: https://id.portal.dev.e-kama.com/
    KEYCLOAK_CLIENT_ID: portal-backend
    KEYCLOAK_REALM_NAME: portal
    KEYCLOAK_CLIENT_SECRET_KEY: HaBSyMd6GXO0FxRnkmXE4NQf5DJOGT3K
    VEHICLE_STATE_API_URL: https://portal.dev.e-kama.com/api/vehicle-states
    VEHICLE_INVENTORY_API_URL: https://portal.dev.e-kama.com/api/vehicle-inventory
    AUTH_SERVICE_API_BASE_URL: https://portal.dev.e-kama.com
    AUTH_SERVICE_API_PATH: /api/auth
    ORG_ID: 95d5fdc5-088f-45cf-be8c-a805940f083a
    PERMISSION_RESOURCE: Fleet
  service:
    enabled: true
    port: 80
    targetPort: 8000
    type: ClusterIP
  probes:
    enabled: false
  serviceMonitor:
    enabled: false
  ingress:
    enabled: true
    host: portal.dev.e-kama.com
    path: /api/fleet-management
    port: 80
    tls: true
    className: nginx-internal
    annotations:
      nginx.ingress.kubernetes.io/proxy-connect-timeout: "3600s"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600s"
      nginx.ingress.kubernetes.io/proxy-body-size: "128m"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128m"
    ## Ingress annotations done as key:value pairs
    ## For a full list of possible ingress annotations, please see
    ## ref: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
