"""nullable org_id

Revision ID: da0f4bed989c
Revises: e56077c4fea5
Create Date: 2022-12-06 10:31:49.572077

"""

# revision identifiers, used by Alembic.
revision = "da0f4bed989c"
down_revision = "e56077c4fea5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
